# Generated by Django 5.0.14 on 2025-10-29 05:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PreMarketMover",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(max_length=10)),
                ("company_name", models.CharField(blank=True, max_length=200)),
                ("news_headline", models.TextField()),
                ("news_source", models.CharField(blank=True, max_length=200)),
                ("news_url", models.URLField(blank=True)),
                (
                    "movement_percent",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "pre_market_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "ai_analysis",
                    models.TextField(
                        blank=True, help_text="AI-generated analysis of the opportunity"
                    ),
                ),
                (
                    "sentiment",
                    models.CharField(
                        blank=True, help_text="bullish, bearish, neutral", max_length=20
                    ),
                ),
                ("strategy_notes", models.TextField(blank=True)),
                (
                    "entry_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "exit_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "profit_loss",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("identified", "Identified"),
                            ("researching", "Researching"),
                            ("ready", "Ready to Trade"),
                            ("executed", "Executed"),
                            ("passed", "Passed"),
                        ],
                        default="identified",
                        max_length=20,
                    ),
                ),
                ("identified_date", models.DateTimeField(auto_now_add=True)),
                ("trade_date", models.DateField(default=django.utils.timezone.now)),
                ("executed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-identified_date"],
                "indexes": [
                    models.Index(
                        fields=["-identified_date"],
                        name="strategies__identif_945f16_idx",
                    ),
                    models.Index(
                        fields=["status"], name="strategies__status_3f9742_idx"
                    ),
                    models.Index(
                        fields=["trade_date"], name="strategies__trade_d_009b66_idx"
                    ),
                ],
            },
        ),
    ]
