# Generated by Django 5.0.14 on 2025-10-29 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("strategies", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="premarketmover",
            name="average_volume",
            field=models.BigIntegerField(
                blank=True, help_text="20-day average volume", null=True
            ),
        ),
        migrations.AddField(
            model_name="premarketmover",
            name="pre_market_volume",
            field=models.BigIntegerField(
                blank=True, help_text="Current pre-market volume", null=True
            ),
        ),
        migrations.AddField(
            model_name="premarketmover",
            name="relative_volume_ratio",
            field=models.FloatField(
                blank=True,
                help_text="RVOL: Pre-market volume / Average volume",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="premarketmover",
            name="spread_percent",
            field=models.FloatField(
                blank=True,
                help_text="Bid-ask spread percentage (liquidity indicator)",
                null=True,
            ),
        ),
    ]
