# Generated by Django 5.0.14 on 2025-10-29 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("research", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TokenUsageLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "endpoint",
                    models.CharField(
                        choices=[
                            ("analyze", "Question Analysis"),
                            ("clarify", "Clarification Generation"),
                            ("respond", "Response Generation"),
                        ],
                        max_length=20,
                    ),
                ),
                ("model", models.CharField(max_length=50)),
                ("prompt_tokens", models.IntegerField()),
                ("completion_tokens", models.IntegerField()),
                ("total_tokens", models.IntegerField()),
                ("cost_estimate", models.DecimalField(decimal_places=6, max_digits=10)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="token_logs",
                        to="research.researchsession",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["-timestamp"], name="ai_service__timesta_e0f89f_idx"
                    ),
                    models.Index(
                        fields=["endpoint"], name="ai_service__endpoin_9fd372_idx"
                    ),
                    models.Index(fields=["model"], name="ai_service__model_d1e5db_idx"),
                ],
            },
        ),
    ]
