# Generated by Django 5.0.14 on 2025-10-29 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("research", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WatchlistItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(max_length=10, unique=True)),
                ("company_name", models.CharField(blank=True, max_length=200)),
                ("added_date", models.DateTimeField(auto_now_add=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("watching", "Watching"),
                            ("researched", "Researched"),
                            ("dismissed", "Dismissed"),
                        ],
                        default="watching",
                        max_length=20,
                    ),
                ),
                (
                    "source_session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="watchlist_items",
                        to="research.researchsession",
                    ),
                ),
            ],
            options={
                "ordering": ["-added_date"],
                "indexes": [
                    models.Index(
                        fields=["symbol"], name="stocks_watc_symbol_778de7_idx"
                    ),
                    models.Index(
                        fields=["status"], name="stocks_watc_status_7bb4bb_idx"
                    ),
                ],
            },
        ),
    ]
